export const iconNames = [
  'search',
  'land',
  'more',
  'favourite',
  'store',
  'arrow-right',
  'arrow-next',
  'arrow-back',
  'close',
  'password-lock',
  'heart',
  'map',
  'list',
  'filter',
  'add-circle',
  'mail',
  'eye-close',
  'eye-open',
  'home',
  'profile',
  'power-button',
  'arrow-down',
  'intro-rings',
  'intro-house',
  'intro-lightbulb',
  'intro-ac',
  'intro-camera',
  'button-gradient',
  'phone',
  'check-circle',
  'button-gradient-green',
  'key',
  'mail-otp',
  'lock-key',
  'check',
  'location-pin',
  'partly-cloudy',
  'plug',
  'settings',
  'devices',
  'weather-card-bg',
] as const;

export type IconName = (typeof iconNames)[number];
