export const iconNames = [
  // Navigation / chrome
  'search',
  'land',
  'more',
  'favourite',
  'store',
  'arrow-right',
  'arrow-next',
  'arrow-back',
  'arrow-down',
  'chevron-right',
  'chevron-down',
  'close',
  'add-circle',
  'plus',
  'filter',
  'sliders',
  'list',
  'grid',
  'trash',
  'edit',
  'refresh',
  // Auth / security
  'mail',
  'mail-otp',
  'eye-close',
  'eye-open',
  'password-lock',
  'lock-key',
  'key',
  'shield',
  // Identity / status
  'home',
  'profile',
  'power-button',
  'check',
  'check-circle',
  'heart',
  'map',
  'location-pin',
  'phone',
  'settings',
  'devices',
  'wifi',
  'zap',
  'bell',
  'clock',
  'calendar',
  'sunrise',
  // Weather
  'sun',
  'moon',
  'cloud',
  'partly-cloudy',
  'cloud-rain',
  'cloud-snow',
  'cloud-fog',
  'cloud-lightning',
  // Device types
  'bulb',
  'fan',
  'thermostat',
  'camera',
  'plug',
  'socket',
  'switch',
  'curtain',
  'dimmer',
  'mesh',
  // Legacy illustration aliases (rendered as clean vectors)
  'intro-rings',
  'intro-house',
  'intro-lightbulb',
  'intro-ac',
  'intro-camera',
  'button-gradient',
  'button-gradient-green',
  'partly-cloudy-bg',
  'weather-card-bg',
] as const;

export type IconName = (typeof iconNames)[number];
